workflows:
  android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.inventory"
    scripts:
      - name: Build APK
        script: |
          cd app
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
