workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      android:
        image: latest
      java: 17
    scripts:
      - echo "Running Gradle build..."
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - 1@ppsspb.ru