workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      java: 17
    scripts:
      - chmod +x ./gradlew
      - ./gradlew clean assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - andrey@ppsspb.ru
