workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      java: 17
    scripts:
      - echo "Fetching dependencies..."
      - flutter pub get
      - echo "Building APK..."
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - andrey@ppsspb.ru
